package posse

// QA pins for ranger-base-qkd0: scripts/tap-formula.sh's `render > "$OUT"` was
// an unguarded truncation of whatever --out was handed. The flag is typed by
// hand at precondition 5 of docs/runbooks/release.md, next to a --checksums
// path; `--out ~/.zshrc` there replaced that file with a Homebrew formula.
//
// Same class as ranger-base-9hyc (see outguard_qa_test.go), one order of
// magnitude smaller: one file, no recursion. The write itself is not the bug
// and is not removed — a release re-renders the same posse.rb every time. What
// is pinned is WHAT may be truncated: a .rb that is absent, empty, or a
// formula a previous run of this script rendered.
//
// Every refusal below is an assertion of ABSENCE (the canary still holds the
// operator's bytes), which a rig that measures nothing also satisfies. So the
// file carries positive witnesses on both sides:
// TestTapFormulaOutGuardControlArmClobbersTheCanary reconstructs the pre-fix
// script by excising the guard between its own markers and shows the same two
// canaries being replaced by a formula, and the accept cases require the run
// to reach the write and leave a formula behind.
//
// Nothing here reads or writes the operator's tree: the canaries, the
// checksums fixture and the rewritten script all live under t.TempDir().

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

const (
	tapOutGuardOpen  = "# >>> out-guard (ranger-base-qkd0)"
	tapOutGuardClose = "# <<< out-guard (ranger-base-qkd0)"
	// Deliberately not internal/rhq.Version: this pin is about --out and must
	// not go red on a release bump.
	tapOutVersion = "9.9.9"
	// The first line the script writes, and the token its guard recognises.
	// Held here as a literal rather than read out of the script, so a rename
	// of the banner has to be made in two places on purpose.
	tapOutMarker = "# posse — generated by scripts/tap-formula.sh"
	// What a canary holds. Byte-identical after a refusal, or the refusal
	// refused nothing.
	tapOutCanaryBody = "the operator's work\n"
)

// tapOutScript returns the script to run: the shipped one when rewrite is nil,
// otherwise a rewritten copy in its own directory.
func tapOutScript(t *testing.T, rewrite func(string) string) string {
	t.Helper()
	const real = "scripts/tap-formula.sh"
	if rewrite == nil {
		return real
	}
	body, err := os.ReadFile(real)
	if err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(t.TempDir(), "tap-formula.sh")
	if err := os.WriteFile(path, []byte(rewrite(string(body))), 0o755); err != nil {
		t.Fatal(err)
	}
	return path
}

func runTapOut(t *testing.T, script, checksums string, args ...string) (exit int, stdout, combined string) {
	t.Helper()
	argv := append([]string{script,
		"--version", "v" + tapOutVersion,
		"--checksums", checksums}, args...)
	cmd := exec.Command("sh", argv...)
	var out, errb strings.Builder
	cmd.Stdout = &out
	cmd.Stderr = &errb
	err := cmd.Run()
	switch e := err.(type) {
	case nil:
		exit = 0
	case *exec.ExitError:
		exit = e.ExitCode()
	default:
		t.Fatalf("sh %s: %v", script, err)
	}
	return exit, out.String(), out.String() + errb.String()
}

// plantFileCanary writes something this script did not write, at path.
func plantFileCanary(t *testing.T, path string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(tapOutCanaryBody), 0o644); err != nil {
		t.Fatal(err)
	}
}

func readTapOutCanary(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("canary %s: %v", path, err)
	}
	return string(b)
}

// tapOutFixture is every --out the refusal table names, rebuilt from scratch.
// It is called once for the paths and again at the top of every subtest: a
// probe that inherits the fixture the last probe mutated measures the last run
// rather than its own.
type tapOutFixture struct {
	zshrc, hand, edited, manifest, adir, link, dangling, danglingTarget string
}

func plantTapOutFixture(t *testing.T, scratch string) tapOutFixture {
	t.Helper()
	f := tapOutFixture{
		// The bead's repro: a dotfile typed where a .rb belongs.
		zshrc: filepath.Join(scratch, ".zshrc"),
		// A .rb that is somebody's, not a previous run's output. This is the
		// case the extension check alone cannot see.
		hand: filepath.Join(scratch, "hand.rb"),
		// A formula whose banner was hand-edited off the top: the guard reads
		// the first line, so a body full of `class Posse` does not license
		// the write.
		edited: filepath.Join(scratch, "edited.rb"),
		// A .txt beside the checksums manifest — the neighbouring flag's path.
		manifest: filepath.Join(scratch, "checksums.txt"),
		// A directory named like the output file. `>` would fail noisily here,
		// but it is refused by name so the message says which mistake it was.
		adir: filepath.Join(scratch, "adir.rb"),
		// A symlink pointing at a canary, and a dangling one. `>` follows
		// both: the first truncates the target, the second creates a file at
		// a path nobody typed.
		link:           filepath.Join(scratch, "link.rb"),
		dangling:       filepath.Join(scratch, "dangling.rb"),
		danglingTarget: filepath.Join(scratch, "not-here.rb"),
	}
	for _, path := range []string{f.zshrc, f.hand, f.edited, f.manifest, f.adir, f.link, f.dangling, f.danglingTarget} {
		if err := os.RemoveAll(path); err != nil {
			t.Fatal(err)
		}
	}
	plantFileCanary(t, f.zshrc)
	plantFileCanary(t, f.hand)
	plantFileCanary(t, f.manifest)
	if err := os.WriteFile(f.edited, []byte(tapOutEditedBody), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(f.adir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(f.hand, f.link); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(f.danglingTarget, f.dangling); err != nil {
		t.Fatal(err)
	}
	return f
}

const tapOutEditedBody = "# my notes\nclass Posse < Formula\nend\n"

func TestTapFormulaOutGuardRefusesWhatItDidNotWrite(t *testing.T) {
	script := tapOutScript(t, nil)
	dir := t.TempDir()
	checksums := writeChecksums(t, dir, tapOutVersion, "")

	scratch := t.TempDir()
	f := plantTapOutFixture(t, scratch)

	for _, tc := range []struct {
		name, out, want string
	}{
		{"the bead's repro", f.zshrc, "a rendered formula is a .rb"},
		{"the neighbouring flag's manifest", f.manifest, "a rendered formula is a .rb"},
		{"a path with no extension", filepath.Join(scratch, "posse"), "a rendered formula is a .rb"},
		{"a hand-written .rb", f.hand, "did not write it and does not know what it is"},
		{"a formula whose banner was edited off", f.edited, "did not write it and does not know what it is"},
		{"a directory", f.adir, "that is a directory"},
		{"the repo-relative dot", ".", "a rendered formula is a .rb"},
		{"the filesystem root", "/", "a rendered formula is a .rb"},
		{"a symlink to a file", f.link, "it is a symlink"},
		{"a dangling symlink", f.dangling, "it is a symlink"},
		{"a parent that is not there", filepath.Join(scratch, "absent", "posse.rb"), "parent directory does not exist"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			plantTapOutFixture(t, scratch)

			exit, stdout, combined := runTapOut(t, script, checksums, "--out", tc.out)
			if exit != 2 {
				t.Errorf("--out %q: exit %d, want 2 (refusal)\n%s", tc.out, exit, combined)
			}
			if !strings.Contains(combined, tc.want) {
				t.Errorf("--out %q: refusal did not say %q\n%s", tc.out, tc.want, combined)
			}
			if strings.Contains(combined, "tap-formula: wrote ") {
				t.Errorf("--out %q: the run reached the write; the guard let it past\n%s", tc.out, combined)
			}
			// A refusal that printed the formula on stdout instead would be a
			// different bug, not a safe one: the operator's `> file` is the
			// truncation this guard is about.
			if strings.Contains(stdout, "class Posse < Formula") {
				t.Errorf("--out %q: a refusal still rendered the formula on stdout\n%s", tc.out, stdout)
			}
			// Every canary in the scratch directory, checked on every case: a
			// guard that refuses the path it was handed while clobbering
			// another one is not a guard.
			for _, canary := range []string{f.zshrc, f.hand, f.manifest} {
				if got := readTapOutCanary(t, canary); got != tapOutCanaryBody {
					t.Errorf("--out %q: canary %s now holds %q", tc.out, canary, got)
				}
			}
			if got := readTapOutCanary(t, f.edited); got != tapOutEditedBody {
				t.Errorf("--out %q: canary %s now holds %q", tc.out, f.edited, got)
			}
			if _, err := os.Stat(f.danglingTarget); !os.IsNotExist(err) {
				t.Errorf("--out %q: the dangling symlink's target was created (stat err: %v)", tc.out, err)
			}
			if fi, err := os.Stat(f.adir); err != nil || !fi.IsDir() {
				t.Errorf("--out %q: the directory canary is gone or is no longer a directory (%v)", tc.out, err)
			}
		})
	}
}

// The accept side. Without it, "refuses everything" would pass every case
// above and the script would be useless rather than safe.
func TestTapFormulaOutGuardStillWritesItsOwnFormula(t *testing.T) {
	script := tapOutScript(t, nil)
	dir := t.TempDir()
	checksums := writeChecksums(t, dir, tapOutVersion, "")
	scratch := t.TempDir()

	t.Run("absent", func(t *testing.T) {
		out := filepath.Join(scratch, "absent.rb")
		exit, _, combined := runTapOut(t, script, checksums, "--out", out)
		if exit != 0 {
			t.Fatalf("--out %s: exit %d, want 0\n%s", out, exit, combined)
		}
		if got := readTapOutCanary(t, out); !strings.HasPrefix(got, tapOutMarker) {
			t.Fatalf("--out %s does not open with the banner: %q", out, firstLine(got))
		}
	})

	t.Run("empty", func(t *testing.T) {
		out := filepath.Join(scratch, "empty.rb")
		if err := os.WriteFile(out, nil, 0o644); err != nil {
			t.Fatal(err)
		}
		exit, _, combined := runTapOut(t, script, checksums, "--out", out)
		if exit != 0 {
			t.Fatalf("--out %s (empty file): exit %d, want 0\n%s", out, exit, combined)
		}
		if got := readTapOutCanary(t, out); !strings.HasPrefix(got, tapOutMarker) {
			t.Fatalf("--out %s does not open with the banner: %q", out, firstLine(got))
		}
	})

	// The round trip that matters: the guard must accept the file the script
	// itself wrote, or the second release of the year is refused by the first.
	// This is also the pin that keeps the renderer's banner and the guard's
	// token the same string.
	t.Run("a formula a previous run rendered", func(t *testing.T) {
		out := filepath.Join(scratch, "rerender.rb")
		if exit, _, combined := runTapOut(t, script, checksums, "--out", out); exit != 0 {
			t.Fatalf("first render: exit %d\n%s", exit, combined)
		}
		first := readTapOutCanary(t, out)
		exit, _, combined := runTapOut(t, script, checksums, "--repo", "someone/else", "--out", out)
		if exit != 0 {
			t.Fatalf("re-render over this script's own output: exit %d, want 0 — a release cannot overwrite the formula the last one wrote\n%s", exit, combined)
		}
		second := readTapOutCanary(t, out)
		if !strings.Contains(second, "someone/else") || second == first {
			t.Fatalf("the re-render did not replace the file:\n%s", firstLine(second))
		}
	})

	// `-` is the default and must stay a pure stdout path: no file, no guard.
	t.Run("stdout", func(t *testing.T) {
		exit, stdout, combined := runTapOut(t, script, checksums, "--out", "-")
		if exit != 0 {
			t.Fatalf("--out -: exit %d, want 0\n%s", exit, combined)
		}
		if !strings.HasPrefix(stdout, tapOutMarker) || !strings.Contains(stdout, "class Posse < Formula") {
			t.Fatalf("--out - did not render the formula on stdout:\n%s", stdout)
		}
		if _, err := os.Stat("-"); !os.IsNotExist(err) {
			t.Fatalf("--out - created a file named \"-\" (stat err: %v)", err)
		}
	})
}

func firstLine(s string) string {
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		return s[:i]
	}
	return s
}

// The positive witness for the whole file: the same fixture, the same
// canaries, the script with the guard cut out. If this does not clobber them,
// the refusals above prove nothing about the guard.
func TestTapFormulaOutGuardControlArmClobbersTheCanary(t *testing.T) {
	var excised bool
	script := tapOutScript(t, func(text string) string {
		open := strings.Index(text, tapOutGuardOpen)
		closed := strings.Index(text, tapOutGuardClose)
		if open < 0 || closed < open {
			return text
		}
		excised = true
		return text[:open] + text[closed+len(tapOutGuardClose):]
	})
	if !excised {
		t.Fatalf("scripts/tap-formula.sh no longer carries the %q / %q markers, so the pre-fix control could not be built — the refusals in this file are measuring nothing", tapOutGuardOpen, tapOutGuardClose)
	}
	dir := t.TempDir()
	checksums := writeChecksums(t, dir, tapOutVersion, "")
	scratch := t.TempDir()

	// One canary per refusal mechanism the guard carries: the name check
	// (a dotfile that is not a .rb) and the content check (a .rb that is
	// somebody's work). Both must be lost without the guard.
	for _, name := range []string{".zshrc", "hand.rb"} {
		t.Run(name, func(t *testing.T) {
			canary := filepath.Join(scratch, name)
			plantFileCanary(t, canary)
			exit, _, combined := runTapOut(t, script, checksums, "--out", canary)
			if exit == 2 {
				t.Fatalf("the unguarded control refused --out %s; the excision did not remove the guard\n%s", canary, combined)
			}
			got := readTapOutCanary(t, canary)
			if got == tapOutCanaryBody {
				t.Fatalf("the unguarded control left %s intact; this rig cannot observe a truncation, so the refusals above are not evidence", canary)
			}
			if !strings.HasPrefix(got, tapOutMarker) {
				t.Fatalf("the unguarded control replaced %s with something that is not the formula: %q", canary, firstLine(got))
			}
		})
	}
}
