package posse

// The darwin store is a COMPOSITE (ADR 0019 D2 as amended 2026-09-01,
// ranger-base-v3qi4; built by ranger-base-5jdzh). Claude Code's own darwin
// secure storage is one store whose name is
// `keychain-with-plaintext-fallback` — the keychain item, then the
// credentials file when the item did not answer — and posse mirrors that
// read order with ONE narrowing: the file only on exit 44 (errSecItemNotFound),
// never on 36 and never on any other failure, because the keychain ACL is per
// binary and posse's 36 speaks about posse's binary rather than about the
// keychain's contents.
//
// What these pin is ADR 0019 V8 and V9. The shape of every row is the same:
// a `security` stub that answers a chosen way, and a fallback file PLANTED
// with a valid envelope carrying a token of its own. That planted file is
// the witness, and it is the whole reason these rows measure anything — a
// fixture the adapter ignores is a pass that measured nothing, so "the file
// is never opened" is asserted by what a read of it WOULD have produced (a
// different token, a different Source, a success where an error is owed) and
// never by the absence of an error.
//
// Every row runs on either box: the stub answers on linux, and `make
// test-linux` proves the darwin branch exactly as a macOS run does (no build
// tags — ADR 0019 D2).

import (
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
	"time"
)

// namesTheFallThrough and namesARefresh are the must-NOT halves of the arms
// below, and they are regexps rather than the whole words they replaced
// ("fallback", "refresh") for the reason ranger-base-g6k5b names on a
// different vocabulary: a banned WORD is walked out from under by a one-word
// respelling of the same meaning, so the pin comes back green on exactly the
// sentence it exists to catch. "the token came from the file it falls back
// to" contains no "fallback"; "Refreshing it will not help" contains no
// lowercase "refresh".
//
// The family, not the stem. A bare "fall" is not enough here — "fell back"
// and "fell through" contain no "fall" — and it is not needed either:
// MEASURED on this tree, none of the four strings these guard (the keychain
// item's Source, the keychain 401, the sourceless 401, the 403) contains
// "fall" in any case, so the width these buy costs no false positive. The
// present-clause arms are untouched: they assert what the fallback 401 must
// SAY, and a wider must-NOT next to them cannot make them read differently.
var (
	namesTheFallThrough = regexp.MustCompile(`(?i)(fall(s|ing|en)?|fell)[ \-]?(back|through)`)
	namesARefresh       = regexp.MustCompile(`(?i)refresh`)
)

// The two envelopes, and they are deliberately not each other: a row that
// cannot tell which store answered has pinned nothing.
const (
	keychainOnlyToken = "token-from-the-keychain-item"
	fallbackOnlyToken = "token-from-the-fallback-file"
)

// fallbackDir points this test's credential resolution at a scratch config
// directory and answers where the composite's fallback file would be.
//
// It is not tidiness. Since the darwin adapter became the composite, a
// `security` that exits 44 consults the file the ENVIRONMENT names — so a
// test that left this to the ambient environment would read the operator's
// own credentials file on any box that has one, and pass or fail on what it
// found there. That file is not hypothetical on the reference box: it is
// regenerated by the runtime on its own schedule (MEASURED 8h06m after a
// delete, ranger-base-xjj9).
//
// It uses t.Setenv, so a test that calls it may not call t.Parallel. The
// secure-storage variable rather than $HOME, because that is the narrowest
// input that moves the file: it changes credentialDir and nothing else in
// the process. It also names a directory, so the keychain item the rows read
// carries the derived suffix (ranger-base-ig4op) — which is the live
// spelling wherever an operator has set either variable, and so the harder
// of the two cases to get right.
func fallbackDir(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	t.Setenv("CLAUDE_SECURESTORAGE_CONFIG_DIR", dir)
	return filepath.Join(dir, ".credentials.json")
}

// plantFallback is that, with the runtime's envelope written into it.
func plantFallback(t *testing.T, blob string) string {
	t.Helper()
	p := fallbackDir(t)
	if err := os.WriteFile(p, []byte(blob), 0o600); err != nil {
		t.Fatal(err)
	}
	return p
}

// ─── V8: the read order, one row per exit ────────────────────────────────────

func TestDarwinCompositeReadsTheFileOnExitFortyFourAndOnNothingElse(t *testing.T) {
	// The fallback envelope is FRESHER than the keychain's, which is ADR
	// 0019 D2's own wording ("the file is never opened even when present and
	// fresher") and the S2/S4 states of its table: a keychain that answers
	// wins over a newer file, because the keychain is the store the runtime
	// itself reads whenever it holds an item.
	keychainExpiry := time.Now().Add(time.Hour).Truncate(time.Millisecond)
	fallbackExpiry := time.Now().Add(90 * 24 * time.Hour).Truncate(time.Millisecond)
	keychainBlob := envelope(keychainOnlyToken, keychainExpiry.UnixMilli())
	fallbackBlob := envelope(fallbackOnlyToken, fallbackExpiry.UnixMilli())

	for _, tc := range []struct {
		name   string
		script string
		// gated builds the stub from posse's own L1 shim instead, which is
		// the one failure that is not a failure of the store at all.
		gated bool
		check func(t *testing.T, tok string, meta CredMeta, err error)
	}{{
		name:   "exit 0: the item answers and the file is never opened, fresher or not",
		script: "#!/bin/sh\ncat <<'JSON'\n" + keychainBlob + "\nJSON\n",
		check: func(t *testing.T, tok string, meta CredMeta, err error) {
			if err != nil {
				t.Fatalf("a keychain that answered is a credential: %v", err)
			}
			if tok != keychainOnlyToken {
				t.Errorf("token = %q, want the keychain item's — the file was read", redact(tok))
			}
			if !strings.Contains(meta.Source, "keychain item") || namesTheFallThrough.MatchString(meta.Source) {
				t.Errorf("Source = %q, want the keychain item's own name", meta.Source)
			}
			// The witness with teeth: the planted file's expiry is three
			// months out and the item's is an hour. An adapter that opened
			// the file and preferred it reports the wrong date here even if
			// it somehow returned the right token.
			if !meta.ExpiresAt.Equal(keychainExpiry.UTC()) {
				t.Errorf("ExpiresAt = %s, want the item's %s — the fresher file was preferred",
					meta.ExpiresAt, keychainExpiry.UTC())
			}
		},
	}, {
		name:   "exit 44: the item is not there, so the file is the store",
		script: "#!/bin/sh\nexit 44\n",
		check: func(t *testing.T, tok string, meta CredMeta, err error) {
			if err != nil {
				t.Fatalf("exit 44 with a fallback file beside it is a credential (S3): %v", err)
			}
			if tok != fallbackOnlyToken {
				t.Errorf("token = %q, want the fallback file's", redact(tok))
			}
			// The Source is the whole point of the fall-through: a 401 on
			// this token has to name where it came from (V9).
			if meta.Source != credentialsFileFallback {
				t.Errorf("Source = %q, want %q", meta.Source, credentialsFileFallback)
			}
			if !meta.ExpiresAt.Equal(fallbackExpiry.UTC()) {
				t.Errorf("ExpiresAt = %s, want the file's %s", meta.ExpiresAt, fallbackExpiry.UTC())
			}
		},
	}, {
		name: "exit 36: user interaction not allowed is about THIS binary, not about the keychain",
		// D2's narrowing, and the row that would re-create the 2026-08-24
		// misdiagnosis if the composite were mirrored literally: after a
		// `make install` drops the ACL, a 36 that fell through would serve a
		// frozen S2 file and call it healthy.
		script: "#!/bin/sh\nexit 36\n",
		check:  unreadableWithTheACLFix,
	}, {
		name:   "exit 1: any other failure is the failure it arrived as",
		script: "#!/bin/sh\nexit 1\n",
		check:  unreadableWithTheACLFix,
	}, {
		name:  "a gate refusal never reaches the file: the item was not reached at all",
		gated: true,
		check: func(t *testing.T, tok string, meta CredMeta, err error) {
			var g *GateRefusal
			if !errors.As(err, &g) {
				t.Fatalf("want *GateRefusal, got %T: %v (token %q)", err, err, redact(tok))
			}
			if cu := CredUnreadableReason(err); cu != nil {
				t.Errorf("posse's own gate wearing the store's class: %+v", cu)
			}
			if tok != "" {
				t.Errorf("a refused read yields no token, got %q", redact(tok))
			}
		},
	}} {
		t.Run(tc.name, func(t *testing.T) {
			plantFallback(t, fallbackBlob)
			bin := ""
			if tc.gated {
				bin = gatedSecurityShim(t)
			} else {
				bin = keychainStub(t, tc.script)
			}
			tok, meta, err := readStore(keychainStoreAt(bin))
			tc.check(t, tok, meta, err)
		})
	}
}

// unreadableWithTheACLFix is today's behaviour, exactly: the class, the
// sentence and the one-line move an operator gets for every keychain failure
// that is not "no such item".
//
// The `never` half is the fall-through assertion. The fallback file is
// planted and holds a valid envelope, so an adapter that consulted it would
// have SUCCEEDED here — the error itself is the witness — and one that
// consulted it and failed would name it in the sentence.
func unreadableWithTheACLFix(t *testing.T, tok string, meta CredMeta, err error) {
	t.Helper()
	if err == nil {
		t.Fatalf("the file was read for a failure that does not fall through: token %q from %q",
			redact(tok), meta.Source)
	}
	cu := CredUnreadableReason(err)
	if cu == nil {
		t.Fatalf("want *CredUnreadable, got %T: %v", err, err)
	}
	if cu.Fix != keychainACLFix {
		t.Errorf("Fix = %q, want today's ACL move %q", cu.Fix, keychainACLFix)
	}
	if !strings.Contains(cu.Store, "keychain item") {
		t.Errorf("Store = %q, want the keychain item's own name", cu.Store)
	}
	if namesTheFallThrough.MatchString(err.Error()) {
		t.Errorf("a failure that never reached the file must not name it, in any spelling: %q", err)
	}
	if tok != "" {
		t.Errorf("a failed read yields no token, got %q", redact(tok))
	}
}

// redact keeps this file's own failure messages under the rule credential.go
// keeps: a token is never printed, and a fixture that turns out to hold a
// real one must not be quoted by the test that caught it.
func redact(tok string) string {
	switch tok {
	case "":
		return ""
	case keychainOnlyToken, fallbackOnlyToken, fakeToken:
		return tok
	}
	return fmt.Sprintf("<%d bytes, not one of this test's fixtures>", len(tok))
}

// ─── V9, first sentence: exit 44 and no file ─────────────────────────────────

// D2's "Not changed" row: 44 with no file stays CredUnreadable — blind, with
// ADR 0018's clock — and never *NoSource. The launcher box is a logged-in box
// by construction, so a vanished item there is an incident and not an
// unconfigured platform, and reporting it as structural absence would switch
// the guard off on the one box that has one.
//
// What it GAINS is the second cause. `security` exiting 44 is two different
// facts wearing one exit code, repaired at opposite ends, and an operator
// told only one of them repairs the wrong end.
func TestDarwinCompositeExitFortyFourWithNoFileIsBlindAndNamesBothCauses(t *testing.T) {
	fallbackDir(t) // named, and nothing planted in it
	_, _, err := readStore(keychainStoreAt(keychainStub(t, "#!/bin/sh\nexit 44\n")))
	if err == nil {
		t.Fatal("an empty keychain with no fallback file is not a credential")
	}
	if ns := NoSourceReason(err); ns != nil {
		t.Fatalf("a vanished item on a logged-in box is blindness, not an unconfigured platform: %+v", ns)
	}
	cu := CredUnreadableReason(err)
	if cu == nil {
		t.Fatalf("want *CredUnreadable, got %T: %v", err, err)
	}
	if PlanFailureOf(err) != PlanFailUnreadable {
		t.Errorf("class = %q, want %q", PlanFailureOf(err), PlanFailUnreadable)
	}
	// The derived item name is in the sentence, so an operator with a
	// suffixed item knows which one to look for in Keychain Access (V12).
	item, _ := keychainItem()
	if !strings.Contains(cu.Store, item) {
		t.Errorf("the sentence must name the item posse actually asked for: Store %q, item %q", cu.Store, item)
	}
	// Both causes, each with its own move.
	for _, want := range []string{
		"it really is gone and claude is running on its fallback credentials file",
		"repair the keychain", "`/login` in claude",
		"keychain ACL may have been dropped by `make install`",
		"grant access when prompted, or run `claude` once",
	} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("the 44-and-no-file sentence must carry %q:\n%q", want, err)
		}
	}
	// The classes this is NOT, in the words that would send an operator at
	// the wrong half of the system (the 2026-08-24 reading).
	for _, never := range []string{"credential stale", "once to refresh", "not entitled"} {
		if strings.Contains(err.Error(), never) {
			t.Errorf("the sentence must not carry another class's move %q: %q", never, err)
		}
	}
	// And no value, ever.
	if strings.Contains(err.Error(), fallbackOnlyToken) || strings.Contains(err.Error(), keychainOnlyToken) {
		t.Errorf("a credential must never appear in a diagnostic: %q", err)
	}
}

// ─── V7 through the fall-through: one parser, two paths, one diagnosis ───────

// The fallback is read through credentialToken like every other store, so an
// envelope posse cannot read produces the okbr shape diagnosis under the
// fallback's own name — and no fix, because a renamed key is not a dropped
// ACL and re-granting one would fix nothing (failShape's rule, ADR 0019 V7).
func TestDarwinCompositeFallbackSharesTheEnvelopeParser(t *testing.T) {
	plantFallback(t, `{"claudeAiOauth":{"refreshToken":"r","expiresAt":1}}`)
	_, _, err := readStore(keychainStoreAt(keychainStub(t, "#!/bin/sh\nexit 44\n")))
	if err == nil {
		t.Fatal("an envelope with no token is not a credential, wherever it was read")
	}
	cu := CredUnreadableReason(err)
	if cu == nil {
		t.Fatalf("want *CredUnreadable, got %T: %v", err, err)
	}
	if cu.Store != credentialsFileFallback {
		t.Errorf("Store = %q, want the store that actually answered (%q)", cu.Store, credentialsFileFallback)
	}
	if cu.Fix != "" {
		t.Errorf("a shape failure carries no store fix (V7): %q", cu.Fix)
	}
	for _, want := range []string{"holds no token in any shape posse knows", "teach credShapes the new name"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("the shape diagnosis is one piece of code for every store; want %q in %q", want, err)
		}
	}
}

// A fallback file that is there and will not open is a READ failure — blind,
// and not structural absence — and it says so under the fallback's name.
func TestDarwinCompositeFallbackThatWillNotOpenIsBlind(t *testing.T) {
	p := fallbackDir(t)
	// A directory at the file's path: os.Stat finds it, os.ReadFile cannot
	// read it. It is the cheapest "present and unreadable" that does not
	// depend on this process's uid (a mode-0 file does not stop root).
	if err := os.MkdirAll(p, 0o700); err != nil {
		t.Fatal(err)
	}
	_, _, err := readStore(keychainStoreAt(keychainStub(t, "#!/bin/sh\nexit 44\n")))
	if ns := NoSourceReason(err); ns != nil {
		t.Fatalf("a file that is there and unreadable is blindness, not absence: %+v", ns)
	}
	cu := CredUnreadableReason(err)
	if cu == nil {
		t.Fatalf("want *CredUnreadable, got %T: %v", err, err)
	}
	if cu.Store != credentialsFileFallback {
		t.Errorf("Store = %q, want %q", cu.Store, credentialsFileFallback)
	}
}

// ─── V9, second sentence: a 401 on a token that fell through ─────────────────

// The class, Stale() and the governance key are unchanged — policy reads no
// diagnosis string (ADR 0018 §2) — and the SENTENCE is not: a 401 on a
// fallback token names the store it came from and the same two causes, so an
// operator does not `/login` at a keychain that was never the problem.
func TestAuthFailureOnAFallbackTokenNamesTheStoreAndBothCauses(t *testing.T) {
	t.Parallel()
	fallback := &AuthFailure{Status: "401 Unauthorized", Code: http.StatusUnauthorized, Source: credentialsFileFallback}
	keychain := &AuthFailure{Status: "401 Unauthorized", Code: http.StatusUnauthorized, Source: `keychain item "Claude Code-credentials"`}
	plain := &AuthFailure{Status: "401 Unauthorized", Code: http.StatusUnauthorized}

	for _, want := range []string{
		"401", "credential stale", "run `claude` once to refresh",
		credentialsFileFallback,
		"either it is gone and claude is living on that file",
		"keychain ACL was dropped by `make install`",
		"Repair the keychain", "`/login` in claude",
	} {
		if !strings.Contains(fallback.Error(), want) {
			t.Errorf("the fallback 401 must say %q:\n%q", want, fallback)
		}
	}
	// The clause is true of exactly one store, so it appears for exactly one
	// store: without this arm the sentence could be unconditional and every
	// assertion above would still pass.
	for _, other := range []*AuthFailure{keychain, plain} {
		if namesTheFallThrough.MatchString(other.Error()) || strings.Contains(other.Error(), "make install") {
			t.Errorf("a 401 on a token that did NOT fall through must carry no fallback clause: %q", other)
		}
	}
	// The class is the same class, and that is the point: the sentence is
	// the diagnostic and nothing here forks policy.
	for _, af := range []*AuthFailure{fallback, keychain, plain} {
		if PlanFailureOf(af) != PlanFailStale || !af.Stale() {
			t.Errorf("the fallback 401 is still the stale class: %q / %v", PlanFailureOf(af), af.Stale())
		}
	}
	// A 403 is not this: a credential that was never entitled is not
	// entitled from either store, so nothing about a refresh may appear and
	// nothing about the fall-through may either — in any spelling of
	// either, which is the half ranger-base-dopyl widened.
	f403 := &AuthFailure{Status: "403 Forbidden", Code: http.StatusForbidden, Source: credentialsFileFallback}
	if namesARefresh.MatchString(f403.Error()) || namesTheFallThrough.MatchString(f403.Error()) {
		t.Errorf("403 keeps its own sentence whatever store answered: %q", f403)
	}
}

// usageEndpointAnswering is the compiled-in usage endpoint, answered in
// memory. It is the only way to pin a sentence that needs a CREDENTIALED
// read: credpin.go credentials exactly one URL (credentialedURL is equality
// against PlanUsageURL), so a reader pointed at a loopback fake never calls
// Token at all and its 401 could carry no Source to name. Nothing leaves the
// box — the RoundTripper answers and no dial is made.
func usageEndpointAnswering(status int) *http.Client {
	return &http.Client{Transport: roundTripFunc(func(r *http.Request) (*http.Response, error) {
		if r.URL.String() != PlanUsageURL {
			return nil, fmt.Errorf("fake usage endpoint answers %s and nothing else", PlanUsageURL)
		}
		return &http.Response{
			StatusCode: status,
			Status:     fmt.Sprintf("%d %s", status, http.StatusText(status)),
			Header:     make(http.Header),
			Body:       io.NopCloser(strings.NewReader("")),
			Request:    r,
		}, nil
	})}
}

// The same sentence through production's own wiring: the seam's Source is
// what the reader threads into the 401, so this fails if the plumbing is
// dropped anywhere between readStore and AuthFailure.
func TestPlanReadThreadsTheFallbackSourceIntoIts401(t *testing.T) {
	t.Parallel()
	r := &AnthropicPlanReader{
		URL:  PlanUsageURL,
		HTTP: usageEndpointAnswering(http.StatusUnauthorized),
		Token: func() (string, CredMeta, error) {
			return fakeToken, CredMeta{Source: credentialsFileFallback, Shape: "claudeAiOauth.accessToken"}, nil
		},
	}
	_, err := r.Read()
	af := AuthFailureReason(err)
	if af == nil {
		t.Fatalf("want *AuthFailure, got %T: %v", err, err)
	}
	if af.Source != credentialsFileFallback {
		t.Fatalf("Source = %q, want the store the reader presented (%q)", af.Source, credentialsFileFallback)
	}
	if !strings.Contains(err.Error(), credentialsFileFallback) {
		t.Errorf("the 401 must name the store it presented: %q", err)
	}
	if strings.Contains(err.Error(), fakeToken) {
		t.Errorf("a credential must never appear in a diagnostic: %q", err)
	}
}

// Surface: the dispatch skip line an unattended parked pass writes (the
// rangerhq-pwpx surface). It prints the error, so the clause reaches the
// operator who is looking at a stopped fleet — which is the moment the
// difference between "the keychain is stale" and "the keychain did not
// answer at all" decides what they go and repair.
func TestBlindSkipOn401FromTheFallbackNamesTheFallbackStore(t *testing.T) {
	r := newBlindRig(t, guardOn)
	r.d.Unattended = true
	pr := planReaderOf(r.d)
	pr.URL = PlanUsageURL
	pr.HTTP = usageEndpointAnswering(http.StatusUnauthorized)
	pr.Token = func() (string, CredMeta, error) {
		return fakeToken, CredMeta{Source: credentialsFileFallback}, nil
	}

	r.at(12 * time.Minute)
	if n := r.run(t); n != 0 {
		t.Fatalf("12m blind parks whatever the class: %d\n%s", n, r.out())
	}
	out := r.out()
	if !strings.Contains(out, "— skipped") {
		t.Fatalf("a parked pass must say why:\n%s", out)
	}
	for _, want := range []string{
		"401", "credential stale", credentialsFileFallback,
		"either it is gone and claude is living on that file",
		"keychain ACL was dropped by `make install`",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("the park line must carry %q, got:\n%s", want, out)
		}
	}
	if strings.Contains(out, fakeToken) {
		t.Errorf("the park line must never carry a credential:\n%s", out)
	}
}

// The governance row the coordinator is pulsed with carries it too: one
// sentence, every surface that prints the error (govern.go guardBlindRow).
func TestGuardBlindRowOn401FromTheFallbackNamesTheFallbackStore(t *testing.T) {
	t.Parallel()
	key, detail := guardBlindRow(10*time.Hour,
		&AuthFailure{Status: "401 Unauthorized", Code: http.StatusUnauthorized, Source: credentialsFileFallback})
	if key != "guard-credential:401" {
		t.Errorf("key = %q, want the credential row's — the class does not move with the sentence", key)
	}
	if !strings.Contains(detail, credentialsFileFallback) {
		t.Errorf("the pulsed row must name the store: %q", detail)
	}
}
