#!/usr/bin/env python3
"""Reproduce docs/notes.d/README.md from fragment contents, without git metadata."""

import argparse
from pathlib import Path
import re
import sys


def render(directory):
    groups = {}
    for path in sorted(directory.glob("*.md")):
        if path.name == "README.md":
            continue
        body = path.read_text()
        heading = re.search(r"^#{1,6}\s+(.+)$", body, re.MULTILINE)
        title = heading.group(1) if heading else path.stem
        date = re.search(r"\b(20\d{2}-(?:0[1-9]|1[0-2])(?:-(?:0[1-9]|[12]\d|3[01]))?)\b", body)
        stamp = date.group(1) if date else ""
        month = stamp[:7] if stamp else "Undated"
        title = title.replace("|", "\\|")
        groups.setdefault(month, []).append((stamp, path.name, title))
    lines = [
        "# Notes fragments", "",
        "Generated by `python3 scripts/notes-index.py`; check with `--check`.",
        "Dates are the first ISO date written in each fragment (including historical",
        "references), not inferred publication dates. Undated fragments sort last.", "",
    ]
    months = sorted((m for m in groups if m != "Undated"), reverse=True)
    if "Undated" in groups:
        months.append("Undated")
    for month in months:
        lines.extend([f"## {month}", ""])
        for stamp, name, title in sorted(groups[month], key=lambda row: (row[0], row[1]), reverse=True):
            suffix = f" — {stamp}" if stamp else ""
            lines.append(f"- [{Path(name).stem}]({name}) — {title}{suffix}")
        lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--directory", type=Path,
                        default=Path(__file__).resolve().parents[1] / "docs/notes.d")
    args = parser.parse_args()
    output = args.directory / "README.md"
    expected = render(args.directory)
    if args.check:
        if not output.exists() or output.read_text() != expected:
            print(f"{output}: stale index; run python3 scripts/notes-index.py", file=sys.stderr)
            return 1
    else:
        output.write_text(expected)
    return 0


if __name__ == "__main__":
    sys.exit(main())
