#!/bin/sh
# Render the Homebrew formula for a posse release (rangerhq-i0n0).
#
# Usage: scripts/tap-formula.sh --version vX.Y.Z [--checksums dist/checksums.txt]
#                               [--repo ranger360ai/posse] [--out <path>]
# Prints Formula/posse.rb to stdout unless --out names a file.
#
# Blast radius: reads a checksums file, writes one file (or stdout). No network,
# no git, no tap. Publishing the rendered formula into ranger360ai/homebrew-tap
# is the OPERATOR's push — see docs/runbooks/release.md.
#
# The formula is generated rather than hand-maintained because four sha256s and
# four URLs change on every release, and a formula with one stale sha fails
# `brew install` for exactly one architecture — the one the person who cut the
# release does not use. Generating it from the same checksums.txt that ships
# beside the tarballs makes that class of mistake unavailable.
set -eu

VERSION=
CHECKSUMS=dist/checksums.txt
REPO=ranger360ai/posse
OUT=-

while [ $# -gt 0 ]; do
	case $1 in
	--version) VERSION=${2:?--version needs a tag}; shift 2 ;;
	--checksums) CHECKSUMS=${2:?--checksums needs a path}; shift 2 ;;
	--repo) REPO=${2:?--repo needs owner/name}; shift 2 ;;
	--out) OUT=${2:?--out needs a path}; shift 2 ;;
	-h|--help) sed -n '2,16p' "$0"; exit 0 ;;
	*) echo "tap-formula: unknown argument: $1" >&2; exit 2 ;;
	esac
done

[ -n "$VERSION" ] || { echo "tap-formula: --version is required" >&2; exit 2; }
case $VERSION in
v[0-9]*) ;;
*) echo "tap-formula: --version must look like vX.Y.Z, got: $VERSION" >&2; exit 2 ;;
esac
bare=${VERSION#v}
[ -f "$CHECKSUMS" ] || { echo "tap-formula: no such checksums file: $CHECKSUMS" >&2; exit 1; }

# Look a tarball's sha up by name. A missing one is fatal: a formula that
# silently omits an architecture is worse than no formula, because it installs
# fine everywhere the author looked.
digest() {
	name=posse_${bare}_$1_$2.tar.gz
	d=$(awk -v n="$name" '$2 == n || $2 == "*"n { print $1; exit }' "$CHECKSUMS")
	[ -n "$d" ] || { echo "tap-formula: $name is not in $CHECKSUMS" >&2; exit 1; }
	printf '%s' "$d"
}

DA=$(digest darwin arm64)
DI=$(digest darwin amd64)
LA=$(digest linux arm64)
LI=$(digest linux amd64)
base=https://github.com/$REPO/releases/download/$VERSION

render() {
	cat <<EOF
# posse — generated by scripts/tap-formula.sh in $REPO. Do not hand-edit:
# the next release overwrites it. Fix the generator instead.
class Posse < Formula
  desc "Dispatcher binding personas, env sets and recipes to herdr and beads"
  homepage "https://github.com/$REPO"
  version "$bare"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "$base/posse_${bare}_darwin_arm64.tar.gz"
      sha256 "$DA"
    end
    on_intel do
      url "$base/posse_${bare}_darwin_amd64.tar.gz"
      sha256 "$DI"
    end
  end

  on_linux do
    on_arm do
      url "$base/posse_${bare}_linux_arm64.tar.gz"
      sha256 "$LA"
    end
    on_intel do
      url "$base/posse_${bare}_linux_amd64.tar.gz"
      sha256 "$LI"
    end
  end

  def install
    bin.install "posse"
    doc.install "README.md", "INSTALL.md"
  end

  # No \`depends_on\` for either substrate, on purpose.
  #
  #   herdr  is not in Homebrew at all, and its own installer refuses to run
  #          under a package manager.
  #   beads  IS in Homebrew — at 1.2.x, which is the WRONG one. 1.2 replaced
  #          the SQLite backend with embedded Dolt, does not read
  #          .beads/beads.db, and auto-inits a stale fork of your queue on the
  #          first call. A \`depends_on "beads"\` here would hand every new
  #          installer a silently forked work graph. posse pins 0.49.1.
  def caveats
    <<~EOS
      posse needs two substrates Homebrew does not install for it:

        herdr >= 0.8      https://herdr.dev
        bd (beads) 0.49.1 EXACTLY — the upstream release binary, NOT
                          \`brew install beads\` (that is 1.2.x, which cannot
                          read .beads/beads.db and forks your queue silently).

      Then stand up an instance:

        posse init
        posse version

      The cold-start runbook is #{doc}/INSTALL.md.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/posse version")
  end
end
EOF
}

if [ "$OUT" = "-" ]; then
	render
else
	render > "$OUT"
	echo "tap-formula: wrote $OUT ($VERSION, $REPO)" >&2
fi
