#!/bin/sh
# Render the Homebrew formula for a posse release (rangerhq-i0n0).
#
# Usage: scripts/tap-formula.sh --version vX.Y.Z [--checksums dist/checksums.txt]
#                               [--repo ranger360ai/posse] [--out <path>]
# Prints Formula/posse.rb to stdout unless --out names a file.
#
#   --out  is TRUNCATED, not appended to, so it is refused unless it names a
#          .rb that is absent, empty, or a formula a previous run rendered.
#          A directory, a symlink, and any file this script did not write are
#          refused outright, and there is no --force (ranger-base-qkd0).
#          `-` (the default) writes to stdout and touches no file.
#
# Blast radius: reads a checksums file, writes one file (or stdout) — and only
# a file that is absent, empty, or a formula this script itself rendered. No
# network, no git, no tap. Publishing the rendered formula into
# ranger360ai/homebrew-tap is the OPERATOR's push — see docs/runbooks/release.md.
#
# The formula is generated rather than hand-maintained because four sha256s and
# four URLs change on every release, and a formula with one stale sha fails
# `brew install` for exactly one architecture — the one the person who cut the
# release does not use. Generating it from the same checksums.txt that ships
# beside the tarballs makes that class of mistake unavailable.
set -eu

VERSION=
CHECKSUMS=dist/checksums.txt
REPO=ranger360ai/posse
OUT=-

# The first line of every formula this script renders. It is both the
# "do not hand-edit" banner and the token the --out guard recognises: a file
# that opens with it is a formula a previous run wrote, and overwriting one of
# those is what a release does every time. One constant, used by the renderer
# and the guard, so the two cannot drift apart and quietly stop matching.
MARKER='# posse — generated by scripts/tap-formula.sh'

while [ $# -gt 0 ]; do
	case $1 in
	--version) VERSION=${2:?--version needs a tag}; shift 2 ;;
	--checksums) CHECKSUMS=${2:?--checksums needs a path}; shift 2 ;;
	--repo) REPO=${2:?--repo needs owner/name}; shift 2 ;;
	--out) OUT=${2:?--out needs a path}; shift 2 ;;
	-h|--help) sed -n '2,23p' "$0"; exit 0 ;;
	*) echo "tap-formula: unknown argument: $1" >&2; exit 2 ;;
	esac
done

[ -n "$VERSION" ] || { echo "tap-formula: --version is required" >&2; exit 2; }
case $VERSION in
v[0-9]*) ;;
*) echo "tap-formula: --version must look like vX.Y.Z, got: $VERSION" >&2; exit 2 ;;
esac
bare=${VERSION#v}
[ -f "$CHECKSUMS" ] || { echo "tap-formula: no such checksums file: $CHECKSUMS" >&2; exit 1; }

# >>> out-guard (ranger-base-qkd0) — the QA control arm excises exactly this
# region, between these two markers, leaving the bare `render > "$OUT"` this
# script shipped with.
#
# `>` truncates whatever it is handed, and --out is typed by hand at
# precondition 5 of docs/runbooks/release.md, one flag away from a --checksums
# path: `--out ~/.zshrc` replaces that file with a Homebrew formula. One file,
# no recursion — a smaller blast radius than ranger-base-9hyc's `rm -rf`, the
# same class of mistake. So the guard is on WHAT may be truncated: a path this
# script could plausibly have written, and nothing else.
#
# The .rb requirement is necessary, never sufficient: it is what refuses a
# typo'd path that does not exist yet (nothing else can see that one), and the
# content check below is what refuses a file that does. There is deliberately
# no --force — the way to overwrite a file of yours is to delete it yourself,
# so the blast radius sits on a command line you wrote.
if [ "$OUT" != "-" ]; then
	case $OUT in
	*.rb) ;;
	*)
		echo "tap-formula: refusing --out $OUT — a rendered formula is a .rb; use - for stdout" >&2
		exit 2
		;;
	esac
	# -L before -e: a dangling symlink fails -e, and `>` through one creates a
	# file where the link points, which is not the path that was typed.
	if [ -L "$OUT" ]; then
		echo "tap-formula: refusing --out $OUT — it is a symlink; name the file it points at" >&2
		exit 2
	fi
	if [ -d "$OUT" ]; then
		echo "tap-formula: refusing --out $OUT — that is a directory" >&2
		exit 2
	fi
	if [ -e "$OUT" ] && [ ! -f "$OUT" ]; then
		echo "tap-formula: refusing --out $OUT — it exists and is not a regular file" >&2
		exit 2
	fi
	# Non-empty and not ours. An empty file is nobody's work, so it is let
	# through the same way an empty directory is in release-artifacts.sh.
	if [ -f "$OUT" ] && [ -s "$OUT" ]; then
		first=$(head -1 "$OUT" 2>/dev/null) || first=
		case $first in
		"$MARKER"*) ;;
		*)
			cat >&2 <<EOF
tap-formula: refusing to overwrite $OUT
  its first line is not "$MARKER",
  so this script did not write it and does not know what it is.
  --out is truncated, not appended to, so it may name only a .rb that is
  absent, empty, or a formula a previous run rendered. If that file is yours
  to lose, remove it yourself and re-run — or use - and redirect.
EOF
			exit 2
			;;
		esac
	fi
	out_parent=$(dirname "$OUT")
	if [ ! -d "$out_parent" ]; then
		echo "tap-formula: --out parent directory does not exist: $out_parent" >&2
		exit 2
	fi
fi
# <<< out-guard (ranger-base-qkd0)

# Look a tarball's sha up by name. A missing one is fatal: a formula that
# silently omits an architecture is worse than no formula, because it installs
# fine everywhere the author looked.
digest() {
	name=posse_${bare}_$1_$2.tar.gz
	d=$(awk -v n="$name" '$2 == n || $2 == "*"n { print $1; exit }' "$CHECKSUMS")
	[ -n "$d" ] || { echo "tap-formula: $name is not in $CHECKSUMS" >&2; exit 1; }
	printf '%s' "$d"
}

DA=$(digest darwin arm64)
DI=$(digest darwin amd64)
LA=$(digest linux arm64)
LI=$(digest linux amd64)
base=https://github.com/$REPO/releases/download/$VERSION

# NO `version` STANZA, on purpose (ranger-base-hza). brew scans the version out
# of the url — `.../v0.3.0/posse_0.3.0_darwin_arm64.tar.gz` — and an explicit
# `version "0.3.0"` beside it is the one thing `brew audit --strict` rejects in
# this formula: "`version 0.3.0` is redundant with version scanned from URL".
# Measured on Homebrew 6.0.20 against all four os/arch pairs, both arms: with
# the stanza, audit fails on all four (which is also the proof that the scan
# resolves 0.3.0 on all four, not just the one this box runs); without it,
# audit is clean on all four, `brew info` reads `stable 0.3.0`, and the install
# and the `test do` block — which asks for `version.to_s` — are unchanged.
render() {
	cat <<EOF
$MARKER in $REPO. Do not hand-edit:
# the next release overwrites it. Fix the generator instead.
class Posse < Formula
  desc "Dispatcher binding personas, env sets and recipes to herdr and beads"
  homepage "https://github.com/$REPO"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "$base/posse_${bare}_darwin_arm64.tar.gz"
      sha256 "$DA"
    end
    on_intel do
      url "$base/posse_${bare}_darwin_amd64.tar.gz"
      sha256 "$DI"
    end
  end

  on_linux do
    on_arm do
      url "$base/posse_${bare}_linux_arm64.tar.gz"
      sha256 "$LA"
    end
    on_intel do
      url "$base/posse_${bare}_linux_amd64.tar.gz"
      sha256 "$LI"
    end
  end

  def install
    bin.install "posse"
    doc.install "README.md", "INSTALL.md"
  end

  # No \`depends_on\` for either substrate, on purpose.
  #
  #   herdr  is not in Homebrew at all, and its own installer refuses to run
  #          under a package manager.
  #   beads  IS in Homebrew — at 1.2.x, which is the WRONG one. 1.2 replaced
  #          the SQLite backend with embedded Dolt, does not read
  #          .beads/beads.db, and auto-inits a stale fork of your queue on the
  #          first call. A \`depends_on "beads"\` here would hand every new
  #          installer a silently forked work graph. posse pins 0.49.1.
  def caveats
    <<~EOS
      posse needs two substrates Homebrew does not install for it:

        herdr >= 0.8      https://herdr.dev
        bd (beads) 0.49.1 EXACTLY — the upstream release binary, NOT
                          \`brew install beads\` (that is 1.2.x, which cannot
                          read .beads/beads.db and forks your queue silently).

      Then stand up an instance:

        posse init
        posse version

      The cold-start runbook is #{doc}/INSTALL.md.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/posse version")
  end
end
EOF
}

if [ "$OUT" = "-" ]; then
	render
else
	render > "$OUT"
	echo "tap-formula: wrote $OUT ($VERSION, $REPO)" >&2
fi
