#!/bin/sh
# Render the Homebrew formula for a posse release (rangerhq-i0n0).
#
# Usage: scripts/tap-formula.sh --version vX.Y.Z [--checksums dist/checksums.txt]
#                               [--repo ranger360ai/posse] [--out <path>]
# Prints Formula/posse.rb to stdout unless --out names a file.
#
#   --out  is TRUNCATED, not appended to, so it is refused unless it names a
#          .rb that is absent, empty, or a formula a previous run rendered.
#          A directory, a symlink, and any file this script did not write are
#          refused outright, and there is no --force (ranger-base-qkd0).
#          `-` (the default) writes to stdout and touches no file.
#
# Blast radius: reads a checksums file, writes one file (or stdout) — and only
# a file that is absent, empty, or a formula this script itself rendered. No
# network, no git, no tap. Publishing the rendered formula into
# ranger360ai/homebrew-tap is the OPERATOR's push — see docs/runbooks/release.md.
#
# The formula is generated rather than hand-maintained because four sha256s and
# four URLs change on every release, and a formula with one stale sha fails
# `brew install` for exactly one architecture — the one the person who cut the
# release does not use. Generating it from the same checksums.txt that ships
# beside the tarballs makes that class of mistake unavailable.
set -eu

VERSION=
CHECKSUMS=dist/checksums.txt
REPO=ranger360ai/posse
OUT=-

# The first line of every formula this script renders. It is both the
# "do not hand-edit" banner and the token the --out guard recognises: a file
# that opens with it is a formula a previous run wrote, and overwriting one of
# those is what a release does every time. One constant, used by the renderer
# and the guard, so the two cannot drift apart and quietly stop matching.
MARKER='# posse — generated by scripts/tap-formula.sh'

while [ $# -gt 0 ]; do
	case $1 in
	--version) VERSION=${2:?--version needs a tag}; shift 2 ;;
	--checksums) CHECKSUMS=${2:?--checksums needs a path}; shift 2 ;;
	--repo) REPO=${2:?--repo needs owner/name}; shift 2 ;;
	--out) OUT=${2:?--out needs a path}; shift 2 ;;
	-h|--help) sed -n '2,23p' "$0"; exit 0 ;;
	*) echo "tap-formula: unknown argument: $1" >&2; exit 2 ;;
	esac
done

[ -n "$VERSION" ] || { echo "tap-formula: --version is required" >&2; exit 2; }
case $VERSION in
v[0-9]*) ;;
*) echo "tap-formula: --version must look like vX.Y.Z, got: $VERSION" >&2; exit 2 ;;
esac
bare=${VERSION#v}
[ -f "$CHECKSUMS" ] || { echo "tap-formula: no such checksums file: $CHECKSUMS" >&2; exit 1; }

# >>> out-guard (ranger-base-qkd0) — the QA control arm excises exactly this
# region, between these two markers, leaving the bare `render > "$OUT"` this
# script shipped with.
#
# `>` truncates whatever it is handed, and --out is typed by hand at
# precondition 5 of docs/runbooks/release.md, one flag away from a --checksums
# path: `--out ~/.zshrc` replaces that file with a Homebrew formula. One file,
# no recursion — a smaller blast radius than ranger-base-9hyc's `rm -rf`, the
# same class of mistake. So the guard is on WHAT may be truncated: a path this
# script could plausibly have written, and nothing else.
#
# The .rb requirement is necessary, never sufficient: it is what refuses a
# typo'd path that does not exist yet (nothing else can see that one), and the
# content check below is what refuses a file that does. There is deliberately
# no --force — the way to overwrite a file of yours is to delete it yourself,
# so the blast radius sits on a command line you wrote.
if [ "$OUT" != "-" ]; then
	case $OUT in
	*.rb) ;;
	*)
		echo "tap-formula: refusing --out $OUT — a rendered formula is a .rb; use - for stdout" >&2
		exit 2
		;;
	esac
	# -L before -e: a dangling symlink fails -e, and `>` through one creates a
	# file where the link points, which is not the path that was typed.
	if [ -L "$OUT" ]; then
		echo "tap-formula: refusing --out $OUT — it is a symlink; name the file it points at" >&2
		exit 2
	fi
	if [ -d "$OUT" ]; then
		echo "tap-formula: refusing --out $OUT — that is a directory" >&2
		exit 2
	fi
	if [ -e "$OUT" ] && [ ! -f "$OUT" ]; then
		echo "tap-formula: refusing --out $OUT — it exists and is not a regular file" >&2
		exit 2
	fi
	# Non-empty and not ours. An empty file is nobody's work, so it is let
	# through the same way an empty directory is in release-artifacts.sh.
	if [ -f "$OUT" ] && [ -s "$OUT" ]; then
		first=$(head -1 "$OUT" 2>/dev/null) || first=
		case $first in
		"$MARKER"*) ;;
		*)
			cat >&2 <<EOF
tap-formula: refusing to overwrite $OUT
  its first line is not "$MARKER",
  so this script did not write it and does not know what it is.
  --out is truncated, not appended to, so it may name only a .rb that is
  absent, empty, or a formula a previous run rendered. If that file is yours
  to lose, remove it yourself and re-run — or use - and redirect.
EOF
			exit 2
			;;
		esac
	fi
	out_parent=$(dirname "$OUT")
	if [ ! -d "$out_parent" ]; then
		echo "tap-formula: --out parent directory does not exist: $out_parent" >&2
		exit 2
	fi
fi
# <<< out-guard (ranger-base-qkd0)

# Look a tarball's sha up by name. A missing one is fatal: a formula that
# silently omits an architecture is worse than no formula, because it installs
# fine everywhere the author looked.
digest() {
	name=posse_${bare}_$1_$2.tar.gz
	d=$(awk -v n="$name" '$2 == n || $2 == "*"n { print $1; exit }' "$CHECKSUMS")
	[ -n "$d" ] || { echo "tap-formula: $name is not in $CHECKSUMS" >&2; exit 1; }
	printf '%s' "$d"
}

DA=$(digest darwin arm64)
DI=$(digest darwin amd64)
LA=$(digest linux arm64)
LI=$(digest linux amd64)
base=https://github.com/$REPO/releases/download/$VERSION

# THE BOTTLE BLOCK (ranger-base-9vg3) — what stops `brew install` needing a
# toolchain. Without it brew takes its build-from-source path and runs the
# FATAL developer-tools diagnostics before it unpacks anything, so on a Mac
# whose Command Line Tools are behind its macOS the install dies with "Your
# Command Line Tools are too outdated" having never read this formula — on the
# route INSTALL.md sells as "a release binary, no Go needed". Measured both
# arms on Homebrew 6.0.20 / macOS 26.4.1 arm64: with this block brew pours,
# without it the same box refuses.
#
# The four tags are scripts/release-artifacts.sh's `bottle_tag()`, and the four
# assets are what it wrote beside the tarballs. A tag missing from the manifest
# is fatal for the same reason a missing tarball is: the formula would install
# fine everywhere the releaser looked and build from source everywhere else.
#
# `cellar :any_skip_relocation` is a claim, and it is true here: the keg is one
# static Go binary and two markdown files, so nothing in it mentions the
# Homebrew prefix and brew has nothing to rewrite. It is also what lets one
# bottle serve /opt/homebrew and /usr/local alike.
bottle_digest() {
	name=posse-${bare}.$1.bottle.tar.gz
	d=$(awk -v n="$name" '$2 == n || $2 == "*"n { print $1; exit }' "$CHECKSUMS")
	[ -n "$d" ] || { echo "tap-formula: $name is not in $CHECKSUMS" >&2; exit 1; }
	printf '%s' "$d"
}

BDA=$(bottle_digest arm64_sonoma)
BDI=$(bottle_digest sonoma)
BLA=$(bottle_digest arm64_linux)
BLI=$(bottle_digest x86_64_linux)

# AN EXPLICIT `version` STANZA, on purpose (ranger-base-63q3) — this REVERSES
# ranger-base-hza's decision to omit it, and the reason it changed is bottles.
#
# Without the stanza brew SCANS the version out of the first url. That scan is
# a property of the BREW ON THE BOX, not of this formula: Homebrew commit
# bae7b0408a (2026-07-28, first tagged in 6.0.14) added the parser that reads
# 0.4.0 out of `.../releases/download/v0.4.0/...`. Every brew from 5.x through
# 6.0.13 falls through to a later heuristic that reads `64` out of
# `posse_0.4.0_darwin_arm64.tar.gz` instead.
#
# Before bottles that only mis-named the keg and the install still worked,
# because the source url is a literal string. The bottle block (ranger-base-9vg3)
# made the scanned string load-bearing: brew builds the bottle filename from
# the formula's own version, so a box that scanned `64` asks root_url for
# posse-64.<tag>.bottle.tar.gz and gets a 404. That is how the published v0.4.0
# failed. ranger-base-w69s measured it end to end on a scratch 6.0.13 against
# the PUBLISHED tap, same box, same formula, one line changed:
#
#   brew 6.0.13, no stanza    -> stable 64     -> install exit 1, curl 404
#   brew 6.0.13, with stanza  -> stable 0.4.0  -> Pouring posse-0.4.0.arm64_sonoma…
#   brew 6.0.20, either way   -> stable 0.4.0
#
# and the parser half is checkable without a scratch prefix at all: load
# Homebrew's own version.rb at each tag and call Version.detect on the
# published url — 6.0.13 answers `64`, 6.0.20 answers `0.4.0`, and the two
# version/parser.rb files are byte-identical. An explicit `@version` is what
# makes the whole question moot on the old brews too: `Downloadable#version`
# in 6.0.13 returns it before it ever consults a url.
#
# THE TRADE, kept written down because it is real and it was decided the other
# way once. On Homebrew 6.0.20 `brew audit --strict` accepts the formula
# without the stanza and, with it, reports (measured on all four os/arch pairs):
#   * Stable: `version 0.4.0` is redundant with version scanned from URL
# Installability on a month-old brew outranks a --strict style finding: the
# audit finding costs a maintainer one known line of output, the omission costs
# every deployer who has not run `brew update` an install that exits 1 with a
# 404 on a url naming a version they never asked for. Ordering the stanza
# before `license` is what settles audit's second complaint about it
# ("`version` should be put before `license`"), so only the redundancy line is
# expected. Renaming the release assets so the OLD heuristic scans them
# correctly was considered and rejected: it would move four published asset
# names, the curl lines in INSTALL.md §1 and release-artifacts.sh, and it can
# only be verified against a brew nobody keeps installed.
#
# The `test do` block asks for `version.to_s` and is unchanged — it read the
# scan before and reads the stanza now.
render() {
	cat <<EOF
$MARKER in $REPO. Do not hand-edit:
# the next release overwrites it. Fix the generator instead.
class Posse < Formula
  desc "Dispatcher binding personas, env sets and recipes to herdr and beads"
  homepage "https://github.com/$REPO"
  version "$bare"
  license "Apache-2.0"

  bottle do
    root_url "$base"
    sha256 cellar: :any_skip_relocation, arm64_sonoma: "$BDA"
    sha256 cellar: :any_skip_relocation, sonoma:       "$BDI"
    sha256 cellar: :any_skip_relocation, arm64_linux:  "$BLA"
    sha256 cellar: :any_skip_relocation, x86_64_linux: "$BLI"
  end

  on_macos do
    on_arm do
      url "$base/posse_${bare}_darwin_arm64.tar.gz"
      sha256 "$DA"
    end
    on_intel do
      url "$base/posse_${bare}_darwin_amd64.tar.gz"
      sha256 "$DI"
    end
  end

  on_linux do
    on_arm do
      url "$base/posse_${bare}_linux_arm64.tar.gz"
      sha256 "$LA"
    end
    on_intel do
      url "$base/posse_${bare}_linux_amd64.tar.gz"
      sha256 "$LI"
    end
  end

  def install
    bin.install "posse"
    doc.install "README.md", "INSTALL.md"
  end

  # No \`depends_on\` for either substrate, on purpose.
  #
  #   herdr  is not in Homebrew at all, and its own installer refuses to run
  #          under a package manager.
  #   beads  IS in Homebrew — at 1.2.x, which is the WRONG one. 1.2 replaced
  #          the SQLite backend with embedded Dolt, does not read
  #          .beads/beads.db, and auto-inits a stale fork of your queue on the
  #          first call. A \`depends_on "beads"\` here would hand every new
  #          installer a silently forked work graph. posse pins 0.49.1.
  def caveats
    <<~EOS
      posse needs two substrates Homebrew does not install for it:

        herdr >= 0.8      https://herdr.dev
        bd (beads) 0.49.1 EXACTLY — the upstream release binary, NOT
                          \`brew install beads\` (that is 1.2.x, which cannot
                          read .beads/beads.db and forks your queue silently).

      Then stand up an instance:

        posse init
        posse version

      The cold-start runbook is #{doc}/INSTALL.md.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/posse version")
  end
end
EOF
}

if [ "$OUT" = "-" ]; then
	render
else
	render > "$OUT"
	echo "tap-formula: wrote $OUT ($VERSION, $REPO)" >&2
fi
